title: Kretov Lab
description: RNA lab at CHU de Québec – Université Laval Research Center
theme: jekyll-theme-minimal
##logo: /assets/images/bg.png
show_downloads: false
##background-image: url("/assets/images/bg.png");
